### ISSUE TITLE
Add `UnusedLet` cop

### ISSUE THREAD

**Issue by backus** [backus/rubocop-rspec#201]

**Comment by backus** [comment]
I spent several days working on an efficient and decent way for statically determining whether lets are used in a certain spec file (using [rubocop's cop force construct](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/force.rb)) and my conclusion is that doing this statically is possible but just not worth it. Even with an efficient static implementation you still have to play it safe if any example group uses `include_examples`, `it_behaves_like`, has rspec metadata, has any form of `send` or dynamic dispatch, etc. It isn't worth all the effort in order to get such a weak check.

I wrote up a proof of concept rspec runner wrapper in about 15 minutes that checks for unused `let`s and it worked beautifully. See https://github.com/mbj/mutant/pull/640, https://github.com/bbatsov/rubocop/pull/3501, and https://github.com/troessner/reek/pull/1087. This implementation was way easier, not prone to a billion forms of incorrect analysis due to dynamic dispatch or includes, and generally just better suited for this job. I'll update this issue when I have a public gem for this dynamic rspec checker :smile:

**Comment by spickermann** [comment]
Hey @backus 

It has been a while since you created this issue and closed is because it was not easily possible and not worth it. But you mentioned that you were able to create a good enough proof of concept in about 5 minutes. 

I am interesting finding unused `let` too, but I have no experience and no idea how such a RSpec runner wrapper might look like. I don't need a solution that supports all edge cases, just something that gives hints what `let` to check. 

Would you be able to share your proof of concept or point me into the right direction?

Btw. this [Stack Overflow question](https://stackoverflow.com/questions/76547589/how-to-find-unnecessary-variable-setup-in-tests-using-rspec) might be of interest in context of this topic.

**Comment by Darhazer** [comment]
@spickermann see https://github.com/dgollahon/rspectre
