### ISSUE TITLE
RSpec/InstanceVariable incorrectly flags assignment too

### ISSUE THREAD

**Issue by bronson** [backus/rubocop-rspec#242]
This line is getting flagged "Use `let` instead of an instance variable":

```ruby
@request.env['REMOTE_ADDR'] = '10.20.30.40'
```

I don't see any way to use let there...  Is there a better way to write this line?

**Comment by bronson** [comment]
Here's the full spec:

```ruby
it 'demands authentication for external ip addresses' do
  @request.env['REMOTE_ADDR'] = '10.20.30.40'
  get :index
  expect(response.status).to eq(401)
end
```

**Comment by backus** [comment]
So part of the issue here is just that the interface for setting up your controller test (I assume that is what this is) requires ivar setup. Is `@request` available via `request`? I'd start there. If it isn't then I would extract a shared context like so

```ruby
RSpec.shared_context 'request from remote ip address' do |ip|
  before do
    # Rails gives me no choice rubocop:disable RSpec/InstanceVariable
    @request.env['REMOTE_ADDR'] = ip
  end
end
```

Then in the specs where you need to do this setup

```ruby
include_context 'request from remote ip address', '10.20.30.40'

it 'demands authentication for external ip addresses' do
  get :index
  expect(response.status).to eq(401)
end
```

Does this help?

**Comment by bronson** [comment]
Yes, removing the `@` works fine.  I didn't even think of that.

It still seems like this test is being a little overzealous...  but, until I actually run into a failing example, I figure everything's fine.

Thanks!  And closing.
